insert into users (name,email,password)
values ('Krishn Kukran','Krishn Kukran','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Keshav','Keshav','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Avni','Avni','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Ansh CHULKAN','Ansh CHULKAN','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Anmol','Anmol','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Ansh','Ansh','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Yash','Yash','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Tejasvi','Tejasvi','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Shanvi','Shanvi','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Vansh','Vansh','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Suhana','Suhana','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Satvik','Satvik','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Abhay','Abhay','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Akshit','Akshit','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Deepanshu','Deepanshu','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Tinku','Tinku','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Sidh','Sidh','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Vedant','Vedant','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Viraz','Viraz','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Sharsti','Sharsti','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Dristi','Dristi','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Aarav','Aarav','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Paryanshu','Paryanshu','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Keshav','Keshav1','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Vansh','Vansh1','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Kanishk','Kanishk','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Atharv','Atharv','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Mayank','Mayank','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Prnav Singh Chhoker','Prnav Singh Chhoker','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Ishu','Ishu','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Vishesh','Vishesh','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Yagya','Yagya','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Akshat','Akshat','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Khusi','Khusi','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Farad','Farad','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
('Jiya','Jiya','$2y$12$KaPVnCHdu6oVEMfGBoE5seDaAXgi1BeW5rPQhsri/uLx3soNfXUN.'),
